### ISSUE TITLE
Suggest vote: renaming this repo to `bianca_workshops` (or `maja_workshops`)

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/bianca_workshops#12]
Currently, this page is called `bianca_workshop` (i.e. singular).

However, recently, it was decided to split the one Bianca workshop into two. 

I suggest to 

 * either rename this repo to `bianca_workshops` (note that GitHub will still redirect from the old URL!),
 * or create a new repo for the intermediate course

A non-existing problem is that then links will break. This is false: as long as there is no new repo called `bianca_workshop`, GitHub will redirect to `bianca_workshops`

**Comment by bclaremar** [comment]
If links won't break I think we can do it already

**Comment by richelbilderbeek** [comment]
Unsure if links will break. 

However, when a user goes to `https://github.com/UPPMAX/bianca_workshop` after this repo gets renamed to -say- `https://github.com/UPPMAX/bianca_workshops` he/she will be redirected by GitHub.

I do know many other repos check for broken links nowadays, so I'd say let's do it (as places that do not care for broken links will, well, sometimes will have broken links)!

**Comment by bclaremar** [comment]
Let's do this some time after Wed 25 Sep!

**Comment by bclaremar** [comment]
Let's do this some time after 11 Nov!

**Comment by richelbilderbeek** [comment]
Seems like we can do this soon, after the evaluations are in, say November 12th, and call it `maja_workshops` :-)

**Comment by richelbilderbeek** [comment]
@bclaremar what about I rename this to `bianca_workshops`? I'll fix all broken links on other repos :+1:

**Comment by bclaremar** [comment]
No need until maja perhaps...

**Comment by bclaremar** [comment]
please rename to bianca_workshops!

Maja will take its time

**Comment by richelbilderbeek** [comment]
It has been done :+1:
