### ISSUE TITLE
Date for intro to bianca: March 19th

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/bianca_workshops#57]
Suggestion:
Sometime in the weeks:
- 11
- 12
- (13)

**Comment by dianaiusan** [comment]
What about Friday, March 14?

**Comment by dianaiusan** [comment]
Please vote in the poll created in the UPPMAX training channel.

**Comment by richelbilderbeek** [comment]
![Screenshot from 2024-12-19 19-36-53](https://github.com/user-attachments/assets/7b2f53da-0e82-482a-84c3-a4b1903eb475)

March 19th is added to the schedule at the page and into the NAISS document :+1:

**Comment by richelbilderbeek** [comment]
Feel free to close :+1:
