### ISSUE TITLE
Date for intermediate Bianca: May 23rd

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/bianca_workshops#58]
Suggestion:
- fri 16 May
- week 21
- early week 22

**Comment by dianaiusan** [comment]
What about Friday, May 23?

**Comment by dianaiusan** [comment]
Please vote in the poll created in the UPPMAX training channel.

**Comment by richelbilderbeek** [comment]
Friday, May 23 is fine by me too :+1:

**Comment by richelbilderbeek** [comment]
![Screenshot from 2024-12-19 19-38-55](https://github.com/user-attachments/assets/cf2ae196-0300-4a84-95ad-a8226d86bb14)

May 23rd is added to at the intermediate course schedule and in the NAISS training document :+1:

**Comment by richelbilderbeek** [comment]
Feel free to close :+1:
